// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHaTL1PzlwHYQqvFTfm4BWtNZcpD95Dxc',
    appId: '1:795901546274:android:50c863d27563649a8f5f7b',
    messagingSenderId: '795901546274',
    projectId: 'mizormor-2c6ef',
    storageBucket: 'mizormor-2c6ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXBs6qxo5-i6gcW-rs1T3DD54fBidUPgU',
    appId: '1:795901546274:ios:754938ea69f3007a8f5f7b',
    messagingSenderId: '795901546274',
    projectId: 'mizormor-2c6ef',
    storageBucket: 'mizormor-2c6ef.appspot.com',
    androidClientId: '795901546274-vv7p9qhtipqa5pvvt0cjgt5ss8gvmnod.apps.googleusercontent.com',
    iosClientId: '795901546274-nlfu2jqu4km8qmuhoq275aoa3u1emav6.apps.googleusercontent.com',
    iosBundleId: 'com.mizormor.mobile',
  );
}
